openapi: 3.0.1
info:
  title: ""
  description: apt
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: sayHello
    description: api to record sales
paths:
  /say-hello:
    post:
      summary: Just return an String
      operationId: sayHelloOperation
      tags:
        - say-hello
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []